### ISSUE TITLE
[Bug]: Light Blue Mana in bulk blast @Create mod does not turn into diamonds

### ISSUE THREAD

**Issue by Trippsterx** [puncrafter/Modpack-Issue-Tracker#2]
### Modpack

MAnA Laboratories

### Describe the bug

When trying to bulk blast the lightblue mana into diamonds with the @Create mod and encased fan it turns into apatite which is very annoying bc i now have to use a blast furnace and a lot of charcole to make diamond

![2023-01-06_21 38 37](https://user-images.githubusercontent.com/115191407/211129678-fdcb7cfe-d125-4b4d-ac20-442f320a1419.png)

![2023-01-06_21 38 46](https://user-images.githubusercontent.com/115191407/211129686-1b5b0370-c1dc-4b58-a49e-ecf5f802acc8.png)

**Comment by puncrafter** [comment]
Unfortunately, this seems to be because create doesn't expect the furnace and blast furnace to have different outputs. You could bring this issue up on create's issue tracker if you'd like, but I'm not sure if they'd fix this kind of bug for 1.16. However, you could always use some automation so that you can have all the wood in the world if you're worried about wasting charcoal just to get diamonds.

**Comment by Trippsterx** [comment]
Thanks, but right after i found that out i set up and automation system for it and it works perfectly
